# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HospitalFaceAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HospitalFaceAI
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'PromiseKit', '~> 6.8'
    pod 'TensorFlowLiteSwift'

end
